# Generated by Django 3.2.4 on 2021-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_siteinfo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
