# Generated by Django 3.2.4 on 2021-07-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_package_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagefeature',
            old_name='Package',
            new_name='package',
        ),
    ]
