# Generated by Django 3.2.4 on 2021-07-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210705_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.package'),
        ),
    ]
