# Generated by Django 3.2.4 on 2021-07-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210705_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cta',
            name='button_link',
        ),
    ]
